#!/bin/bash
set -e

#Ensure this script is being run as root
if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as superuser." >&2
    exit 1
fi

# Check for Python
if ! command -v python3 &>/dev/null; then
    sudo apt-get install python3
    exit 1
fi


# Check and install required dependencies
DEPENDENCIES=("python3-paramiko" "python3-yaml" "dos2unix" )

for dep in "${DEPENDENCIES[@]}"; do
    if ! dpkg-query -W -f='${Status}' "$dep" 2>/dev/null | grep "install ok installed" > /dev/null; then
        echo "Dependency $dep is missing. Installing..."
        sudo apt-get install -y "$dep"
    else
        echo "Dependency $dep is already installed."
    fi
done

# creating a directory to store program data
install -d -m 755 /var/lib/mikro-helper

echo "Preinst completed"
exit 0