#!/bin/bash
dos2unix $SCRIPT_DIR/mikro-helper.py

#add to PATH
export PATH=\$PATH:/usr/bin

chmod +x /usr/bin/mikro-helper.py

#create alias
echo "alias mikro-helper='python3 usr/bin/mikro-helper.py'" >> ~/.bashrc
source ~/.bashrc

